"""add_category

Revision ID: 29c794a90ac3
Revises: 891f46dd645a
Create Date: 2025-08-16 22:49:06.131757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Text, TIMESTAMP, UUID
import uuid
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = '29c794a90ac3'
down_revision: Union[str, Sequence[str], None] = '891f46dd645a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('files', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'files', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
    
    # ### commands to insert initial data ###
    categories_table = table('categories',
        column('id', UUID),
        column('name', String),
        column('slug', String),
        column('description', Text),
        column('created_at', TIMESTAMP)
    )
    
    op.bulk_insert(categories_table, [
        {
            'id': '4b681b59-6521-48f2-aa24-f4677874be5c',
            'name': '0+',
            'slug': '0-plus',
            'description': 'Content suitable for all ages',
            'created_at': datetime.utcnow()
        },
        {
            'id': '188c209c-a486-4df9-9094-73160dfaa25d',
            'name': '16+',
            'slug': '16-plus',
            'description': 'Content suitable for ages 16 and above',
            'created_at': datetime.utcnow()
        },
        {
            'id': 'f3aeb8c5-7c00-452a-84af-cd8c1fef4993',
            'name': '18+',
            'slug': '18-plus',
            'description': 'Content suitable for ages 18 and above',
            'created_at': datetime.utcnow()
        }
    ])
    # ### end commands to insert initial data ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удалить данные перед удалением таблицы
    op.execute("DELETE FROM categories")
    
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###