"""add_dash_video

Revision ID: 6c542258a54b
Revises: f8c2f58f9091
Create Date: 2025-08-30 15:38:33.560279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c542258a54b'
down_revision: Union[str, Sequence[str], None] = 'f8c2f58f9091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('transcoding_status', sa.String(length=20), nullable=True))
    op.add_column('files', sa.Column('dash_manifest_path', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('hls_manifest_path', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('renditions_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'renditions_info')
    op.drop_column('files', 'hls_manifest_path')
    op.drop_column('files', 'dash_manifest_path')
    op.drop_column('files', 'transcoding_status')
    # ### end Alembic commands ###
